### ISSUE TITLE
NetVLAD

### ISSUE THREAD

**Issue by lsl1229840757** [ekingedik/loupe-pytorch#1]
when I use NetVLAD, I find that this model get reshaped_input in this way:
```python
reshaped_input = input.view(-1, self.feature_size)
```
but image is **channel first** in pytorch, like the screenshot below, although the above operation can get the same shape tensor, this tensor is wrong

![image](https://user-images.githubusercontent.com/35564869/101567735-55e4ab00-3a0c-11eb-8fd1-ace4f5217dff.png)

**Comment by ekingedik** [comment]
Hello,

As stated in the source code, you need to reshape your input into  'batch_size' x 'max_samples' x 'feature_size' format before feeding it into NetVLAD layers. The specific implementation in this repo does not focus on image data.

Best,
Ekin
